---
version: '2'
services:
    ansible-template-packer:
        image: ansible-template-packer 
        build: .
        privileged: true
        user: root
        network_mode: host
        #        ports:
        #            - "127.0.0.1:5900:5900"        
        volumes: 
            - /build:/build
            - /dev/kvm:/dev/kvm:rw
            - /dev/net/tun:/dev/net/tun:rw
              #        environment:
              #            - PACKER_LOG=1
